chest:
  local_path: "/media/chest"
  services_path: "/media/chest/srv"
timecapsule:
  local_path: "{{ chest.local_path }}/time_capsule"
  share_name: time_capsule
  avahi_dir: "{{ common.services_path }}/avahi-timecapsule"